//Create User
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "samantha",
    "email": "samantha@gmail.com",
    "password": "123456",
    "confPassword": "123456",
    "role": "vendedor"
}

###
//Get All User
Get http://localhost:5000/users

###
//Get Single User
Get http://localhost:5000/users/556ccfb9-5629-4c57-b565-1e350cfe20e8

###
//Actualizar User
PATCH  http://localhost:5000/users/556ccfb9-5629-4c57-b565-1e350cfe20e8
Content-Type: application/json

{
    "name": "Javis Actualizado Benavente",
    "email": "benavente@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "vendedor"
}

###
//Deleted User
DELETE http://localhost:5000/users/556ccfb9-5629-4c57-b565-1e350cfe20e8


###
//Login User
POST https://backend-grupo-mr-production-2c03.up.railway.app/login
Content-Type: application/json

{
    "email": "javier@gmail.com",
    "password": "123456"
}

###
//Data User
GET  http://localhost:5000/me

###
//cerrar sesion
DELETE  http://localhost:5000/logout

###
//Get All Products
GET http://localhost:5000/products


###
//Get Single Products
GET http://localhost:5000/products/7cc6a52d-1f72-4c92-9183-07c975f586a0


###
//Create Products
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product vendedor",
    "price": 120.00
    
}


###
// Obtener todos los clientes
GET http://localhost:5000/clients


###
// Obtener un cliente por ID
GET http://localhost:5000/clients/


###
// Eliminar un cliente
DELETE http://localhost:5000/clients/


###
// Crear un nuevo cliente
POST http://localhost:5000/clients
Content-Type: application/json

{
   "fullName": "Juan Pérez",
    "contactName": "María López",
    "contactPhone": "123456789",
    "position": "Manager"
}


### Obtener todas las empresas
GET http://localhost:5000/companies


### Obtener una empresa por ID
GET http://localhost:5000/companies

### Actualizar una empresa por ID
PUT http://localhost:5000/companies/


### Eliminar una empresa por ID
DELETE http://localhost:5000/companies/

### Crear una nueva empresa
POST http://localhost:5000/companies
Content-Type: application/json

{
    "companyName": "Tech Solutions",
    "phone": "123456789",
    "interactionDate": "2023-08-01",
    "product": "Software Development",
    "paymentMethod": "Transferencia",
    "branch": "Main Office",
    "prospects": "New clients"
}


### Obtener todas las unidades de negocio
GET http://localhost:5000/business-units



### Crear una nueva unidad de negocio
POST http://localhost:5000/business-units
Content-Type: application/json

{
    "unitName": "Plastico",
    "description": "Descripción del servicioT",
    "sales": 1500.00
}


### Eliminar una unidad de negocio por ID
DELETE http://localhost:5000/business-units/e4a4dbe5-dddd-428e-9ca7-af3c902faee8


###
POST http://localhost:5000/events
Content-Type: application/json

{
  "description": "Visitar cliente en la mañana",
  "date": "2024-08-12",
  "timeOfDay": "Mañana"
}

###
GET http://localhost:5000/events
